### ISSUE TITLE
Firefox 33.1.1 on OSX showing OS and custom scrollbars

### ISSUE THREAD

**Issue by levibuzolic** [ojame/react-scrollbars#21]
![scrollbars-firefox](https://cloud.githubusercontent.com/assets/721323/6612766/6018c00a-c8d6-11e4-9ae8-09ad9bbdb2e7.gif)

**Comment by levibuzolic** [comment]
Might be a non-issue, appears to be fixed in Firefox 36.

![giphy-18](https://cloud.githubusercontent.com/assets/721323/6612799/da8e9ecc-c8d6-11e4-9262-33d5dbc8d628.gif)

**Comment by ojame** [comment]
Because firefox (by default) silently updates, I feel this isn't a major issue at the moment.
